replicaCount: 1
image:
  repository: ghcr.io/himanshusingh444/go-app
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: NodePort
  port: 8080
  nodePort: 30080
resources:
  limits:
    cpu: "0.3"
    memory: "256Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"
probes:
  liveness:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5                            